project_id = "cndrzyherqlzfxggufnh"

[functions.create-link-token]
verify_jwt = true

[functions.exchange-public-token]
verify_jwt = true

[functions.get-plaid-accounts]
verify_jwt = true

[functions.import-plaid-transactions]
verify_jwt = true

[functions.sync-plaid-transactions]
verify_jwt = true

[functions.create-square-subscription]
verify_jwt = true

[functions.cancel-square-subscription]
verify_jwt = true
