// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cndrzyherqlzfxggufnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZHJ6eWhlcnFsemZ4Z2d1Zm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzYyMzMsImV4cCI6MjA3MzQ1MjIzM30.0CBhxUKhQM-LOJQpoEGEzc0INtk680C2Y-_ypr_TE4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});